apiVersion: v1
kind: Secret
metadata:
  name: zeni-x-secrets
  namespace: zeni-x
type: Opaque
stringData:
  # 这些密码需要替换为实际值，或者从其他 Secret 引用
  MYSQL_ROOT_PASSWORD: "DAZezFX6kw3VWaCCR0kvR03fuBTV/wGj"
  REDIS_PASSWORD: "HL+4E5JXv2zGQ1TivobhKcNvXtdSB189"

