apiVersion: v1
kind: Service
metadata:
  name: zeni-x
  namespace: zeni-x
  labels:
    app: zeni-x
spec:
  type: NodePort
  selector:
    app: zeni-x
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: api
    port: 8080
    targetPort: 8080
    nodePort: 30088

