namespace: zeni-x-dev

global:
  imageRegistry: registry.local
  environment: dev

frontend:
  image:
    tag: latest

backend:
  image:
    tag: latest

service:
  frontend:
    nodePort: 30080
  backend:
    nodePort: 30088

ingress:
  className: traefik
  hosts:
    - host: zeni-x.local
