namespace: zeni-x-uat

global:
  imageRegistry: registry.cn-hangzhou.aliyuncs.com
  environment: uat

frontend:
  image:
    tag: uat

backend:
  image:
    tag: uat
  resources:
    limits:
      memory: 512Mi
      cpu: 400m

service:
  frontend:
    nodePort: 30280
  backend:
    nodePort: 30288

ingress:
  className: alb
  hosts:
    - host: zeni-x.uat.yunizeni.com
