namespace: zeni-x-prod

global:
  imageRegistry: registry.cn-hangzhou.aliyuncs.com
  environment: prod

frontend:
  image:
    tag: stable

backend:
  image:
    tag: stable

service:
  frontend:
    nodePort: 30380
  backend:
    nodePort: 30388

ingress:
  className: alb
  hosts:
    - host: zeni-x.yunizeni.com
