namespace: zeni-x-test

global:
  imageRegistry: alexxiong
  environment: test

frontend:
  image:
    tag: test

backend:
  image:
    tag: test

service:
  frontend:
    nodePort: 30180
  backend:
    nodePort: 30188

persistence:
  storageClass: "longhorn"

ingress:
  className: traefik
  hosts:
    - host: zeni-x.inner.inspirai.store
