apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zeni-x-uat

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

patches:
  - path: patch.yaml

images:
  - name: registry.local/zeni-x-frontend
    newTag: uat
  - name: registry.local/zeni-x-backend
    newTag: uat

