{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zeni-x.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "zeni-x.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
{{- end }}
