apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeni-x.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "zeni-x.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "zeni-x.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.ports.http.name }}
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: {{ .Values.service.ports.http.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.http.nodePort }}
      nodePort: {{ .Values.service.ports.http.nodePort }}
      {{- end }}
    - name: {{ .Values.service.ports.api.name }}
      port: {{ .Values.service.ports.api.port }}
      targetPort: {{ .Values.service.ports.api.targetPort }}
      protocol: {{ .Values.service.ports.api.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.api.nodePort }}
      nodePort: {{ .Values.service.ports.api.nodePort }}
      {{- end }}
