{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: zeni-x-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- if .Values.secret.databasePassword }}
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword | b64enc | quote }}
{{- end }}
{{- if .Values.secret.apiKey }}
  API_KEY: {{ .Values.secret.apiKey | b64enc | quote }}
{{- end }}
{{- if .Values.secret.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | b64enc | quote }}
{{- end }}
{{- if .Values.secret.data }}
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
