{{- if .Values.rbac.create }}
{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: zeni-x
{{- end }}
{{- end }}
