server:
  port: "15080"
  mode: debug

sqlite:
  path: ./data/zeni-x.db

mysql:
  host: localhost
  port: 3306
  user: root
  password: "root123"
  database: ""

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

mongodb:
  host: localhost
  port: 27017
  user: admin
  password: "admin123"
  database: ""

minio:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: "minioadmin123"
  use_ssl: false

