{{- if .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: zeni-x
    environment: {{ .Values.global.environment | default "dev" }}
{{- end }}
