apiVersion: v1
kind: Service
metadata:
  name: zeni-x
  namespace: {{ .Values.namespace }}
  labels:
    app: zeni-x
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.frontend.nodePort }}
      nodePort: {{ .Values.service.frontend.nodePort }}
      {{- end }}
    - name: api
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.backend.nodePort }}
      nodePort: {{ .Values.service.backend.nodePort }}
      {{- end }}
  selector:
    app: zeni-x
